"""create stage 1 schema

Revision ID: f65224efb871
Revises:
Create Date: 2026-05-05 10:58:00.267805
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

from sqlalchemy.dialects import postgresql

revision: str = 'f65224efb871'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('day_key', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_code', 'day_key', name='uq_daily_reports_domain_day')
    )
    op.create_index(op.f('ix_daily_reports_day_key'), 'daily_reports', ['day_key'], unique=False)
    op.create_index(op.f('ix_daily_reports_domain_code'), 'daily_reports', ['domain_code'], unique=False)
    op.create_index(op.f('ix_daily_reports_global_id'), 'daily_reports', ['global_id'], unique=True)
    op.create_index(op.f('ix_daily_reports_status'), 'daily_reports', ['status'], unique=False)
    op.create_index(op.f('ix_daily_reports_sync_policy'), 'daily_reports', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_daily_reports_visibility_scope'), 'daily_reports', ['visibility_scope'], unique=False)
    op.create_table('data_sources',
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_focus_id', sa.Integer(), nullable=False),
    sa.Column('backfill_days', sa.Integer(), nullable=False),
    sa.Column('credential_ref', sa.String(length=128), nullable=True),
    sa.Column('fetch_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('paper_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('source_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_domain_code'), 'data_sources', ['domain_code'], unique=False)
    op.create_index(op.f('ix_data_sources_global_id'), 'data_sources', ['global_id'], unique=True)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=False)
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_data_sources_sync_policy'), 'data_sources', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_data_sources_visibility_scope'), 'data_sources', ['visibility_scope'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('recommendation_runs',
    sa.Column('run_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_runs_domain_code'), 'recommendation_runs', ['domain_code'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_global_id'), 'recommendation_runs', ['global_id'], unique=True)
    op.create_index(op.f('ix_recommendation_runs_run_key'), 'recommendation_runs', ['run_key'], unique=True)
    op.create_index(op.f('ix_recommendation_runs_status'), 'recommendation_runs', ['status'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_sync_policy'), 'recommendation_runs', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_visibility_scope'), 'recommendation_runs', ['visibility_scope'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('sync_inbox',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('source_instance_id', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_inbox_event_id'), 'sync_inbox', ['event_id'], unique=True)
    op.create_index(op.f('ix_sync_inbox_object_id'), 'sync_inbox', ['object_id'], unique=False)
    op.create_index(op.f('ix_sync_inbox_object_type'), 'sync_inbox', ['object_type'], unique=False)
    op.create_index(op.f('ix_sync_inbox_source_instance_id'), 'sync_inbox', ['source_instance_id'], unique=False)
    op.create_index(op.f('ix_sync_inbox_status'), 'sync_inbox', ['status'], unique=False)
    op.create_table('sync_outbox',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_outbox_domain_code'), 'sync_outbox', ['domain_code'], unique=False)
    op.create_index(op.f('ix_sync_outbox_event_id'), 'sync_outbox', ['event_id'], unique=True)
    op.create_index(op.f('ix_sync_outbox_object_id'), 'sync_outbox', ['object_id'], unique=False)
    op.create_index(op.f('ix_sync_outbox_object_type'), 'sync_outbox', ['object_type'], unique=False)
    op.create_index(op.f('ix_sync_outbox_operation'), 'sync_outbox', ['operation'], unique=False)
    op.create_index(op.f('ix_sync_outbox_status'), 'sync_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_sync_outbox_sync_policy'), 'sync_outbox', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_sync_outbox_visibility_scope'), 'sync_outbox', ['visibility_scope'], unique=False)
    op.create_table('sync_runs',
    sa.Column('package_id', sa.String(length=128), nullable=False),
    sa.Column('source_instance_id', sa.String(length=64), nullable=False),
    sa.Column('target_instance_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('counts_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_direction'), 'sync_runs', ['direction'], unique=False)
    op.create_index(op.f('ix_sync_runs_package_id'), 'sync_runs', ['package_id'], unique=True)
    op.create_index(op.f('ix_sync_runs_source_instance_id'), 'sync_runs', ['source_instance_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_runs_target_instance_id'), 'sync_runs', ['target_instance_id'], unique=False)
    op.create_table('users',
    sa.Column('external_provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('employee_no', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_employee_no'), 'users', ['employee_no'], unique=False)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_index(op.f('ix_users_external_provider'), 'users', ['external_provider'], unique=False)
    op.create_index(op.f('ix_users_global_id'), 'users', ['global_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('weekly_reports',
    sa.Column('week_key', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_code', 'week_key', name='uq_weekly_reports_domain_week')
    )
    op.create_index(op.f('ix_weekly_reports_domain_code'), 'weekly_reports', ['domain_code'], unique=False)
    op.create_index(op.f('ix_weekly_reports_global_id'), 'weekly_reports', ['global_id'], unique=True)
    op.create_index(op.f('ix_weekly_reports_status'), 'weekly_reports', ['status'], unique=False)
    op.create_index(op.f('ix_weekly_reports_sync_policy'), 'weekly_reports', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_weekly_reports_visibility_scope'), 'weekly_reports', ['visibility_scope'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_key'), 'weekly_reports', ['week_key'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_id'), 'audit_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_type'), 'audit_logs', ['object_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('editorial_actions',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_actions_action_type'), 'editorial_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_editorial_actions_object_id'), 'editorial_actions', ['object_id'], unique=False)
    op.create_index(op.f('ix_editorial_actions_object_type'), 'editorial_actions', ['object_type'], unique=False)
    op.create_index(op.f('ix_editorial_actions_user_id'), 'editorial_actions', ['user_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('export_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_domain_code'), 'export_jobs', ['domain_code'], unique=False)
    op.create_index(op.f('ix_export_jobs_export_type'), 'export_jobs', ['export_type'], unique=False)
    op.create_index(op.f('ix_export_jobs_global_id'), 'export_jobs', ['global_id'], unique=True)
    op.create_index(op.f('ix_export_jobs_requested_by_id'), 'export_jobs', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_export_jobs_sync_policy'), 'export_jobs', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_export_jobs_visibility_scope'), 'export_jobs', ['visibility_scope'], unique=False)
    op.create_table('raw_items',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('entry_key', sa.String(length=255), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'entry_key', name='uq_raw_items_source_entry')
    )
    op.create_index(op.f('ix_raw_items_data_source_id'), 'raw_items', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_raw_items_domain_code'), 'raw_items', ['domain_code'], unique=False)
    op.create_index(op.f('ix_raw_items_entry_key'), 'raw_items', ['entry_key'], unique=False)
    op.create_index(op.f('ix_raw_items_fetched_at'), 'raw_items', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_items_global_id'), 'raw_items', ['global_id'], unique=True)
    op.create_index(op.f('ix_raw_items_source_type'), 'raw_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_raw_items_sync_policy'), 'raw_items', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_raw_items_visibility_scope'), 'raw_items', ['visibility_scope'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sync_conflicts',
    sa.Column('sync_run_id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('local_revision', sa.Integer(), nullable=False),
    sa.Column('incoming_revision', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('local_value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('incoming_value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_conflicts_object_id'), 'sync_conflicts', ['object_id'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_object_type'), 'sync_conflicts', ['object_type'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_status'), 'sync_conflicts', ['status'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_sync_run_id'), 'sync_conflicts', ['sync_run_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('news_items',
    sa.Column('raw_item_id', sa.String(length=36), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('focus_id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('normalization_status', sa.String(length=32), nullable=False),
    sa.Column('normalization_notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_active'), 'news_items', ['active'], unique=False)
    op.create_index(op.f('ix_news_items_data_source_id'), 'news_items', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_news_items_dedupe_key'), 'news_items', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_news_items_domain_code'), 'news_items', ['domain_code'], unique=False)
    op.create_index(op.f('ix_news_items_global_id'), 'news_items', ['global_id'], unique=True)
    op.create_index(op.f('ix_news_items_normalization_status'), 'news_items', ['normalization_status'], unique=False)
    op.create_index(op.f('ix_news_items_raw_item_id'), 'news_items', ['raw_item_id'], unique=False)
    op.create_index(op.f('ix_news_items_source_type'), 'news_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_news_items_sync_policy'), 'news_items', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_news_items_visibility_scope'), 'news_items', ['visibility_scope'], unique=False)
    op.create_table('dedupe_groups',
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('winner_news_item_id', sa.String(length=36), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['winner_news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedupe_groups_dedupe_key'), 'dedupe_groups', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_dedupe_groups_domain_code'), 'dedupe_groups', ['domain_code'], unique=False)
    op.create_index(op.f('ix_dedupe_groups_global_id'), 'dedupe_groups', ['global_id'], unique=True)
    op.create_index(op.f('ix_dedupe_groups_sync_policy'), 'dedupe_groups', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_dedupe_groups_visibility_scope'), 'dedupe_groups', ['visibility_scope'], unique=False)
    op.create_table('insights',
    sa.Column('news_item_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_domain_code'), 'insights', ['domain_code'], unique=False)
    op.create_index(op.f('ix_insights_global_id'), 'insights', ['global_id'], unique=True)
    op.create_index(op.f('ix_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_news_item_id'), 'insights', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_insights_sync_policy'), 'insights', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_insights_visibility_scope'), 'insights', ['visibility_scope'], unique=False)
    op.create_table('dedupe_group_items',
    sa.Column('dedupe_group_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('duplicate_reason', sa.Text(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dedupe_group_id'], ['dedupe_groups.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_group_id', 'news_item_id', name='uq_dedupe_group_news_item')
    )
    op.create_index(op.f('ix_dedupe_group_items_dedupe_group_id'), 'dedupe_group_items', ['dedupe_group_id'], unique=False)
    op.create_index(op.f('ix_dedupe_group_items_news_item_id'), 'dedupe_group_items', ['news_item_id'], unique=False)
    op.create_table('strategic_implications',
    sa.Column('insight_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('implication_type', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_implications_domain_code'), 'strategic_implications', ['domain_code'], unique=False)
    op.create_index(op.f('ix_strategic_implications_global_id'), 'strategic_implications', ['global_id'], unique=True)
    op.create_index(op.f('ix_strategic_implications_implication_type'), 'strategic_implications', ['implication_type'], unique=False)
    op.create_index(op.f('ix_strategic_implications_insight_id'), 'strategic_implications', ['insight_id'], unique=False)
    op.create_index(op.f('ix_strategic_implications_sync_policy'), 'strategic_implications', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_strategic_implications_visibility_scope'), 'strategic_implications', ['visibility_scope'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('dedupe_group_id', sa.String(length=36), nullable=False),
    sa.Column('dedupe_group_item_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('topic_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=False),
    sa.Column('diversity_score', sa.Float(), nullable=False),
    sa.Column('source_score', sa.Float(), nullable=False),
    sa.Column('heat_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dedupe_group_id'], ['dedupe_groups.id'], ),
    sa.ForeignKeyConstraint(['dedupe_group_item_id'], ['dedupe_group_items.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_items_dedupe_group_id'), 'recommendation_items', ['dedupe_group_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_dedupe_group_item_id'), 'recommendation_items', ['dedupe_group_item_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_domain_code'), 'recommendation_items', ['domain_code'], unique=False)
    op.create_index(op.f('ix_recommendation_items_global_id'), 'recommendation_items', ['global_id'], unique=True)
    op.create_index(op.f('ix_recommendation_items_news_item_id'), 'recommendation_items', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_run_id'), 'recommendation_items', ['run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_selected'), 'recommendation_items', ['selected'], unique=False)
    op.create_index(op.f('ix_recommendation_items_sync_policy'), 'recommendation_items', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_recommendation_items_visibility_scope'), 'recommendation_items', ['visibility_scope'], unique=False)
    op.create_table('requirements',
    sa.Column('strategic_implication_id', sa.String(length=36), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategic_implication_id'], ['strategic_implications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_domain_code'), 'requirements', ['domain_code'], unique=False)
    op.create_index(op.f('ix_requirements_global_id'), 'requirements', ['global_id'], unique=True)
    op.create_index(op.f('ix_requirements_owner_user_id'), 'requirements', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_requirements_priority'), 'requirements', ['priority'], unique=False)
    op.create_index(op.f('ix_requirements_status'), 'requirements', ['status'], unique=False)
    op.create_index(op.f('ix_requirements_strategic_implication_id'), 'requirements', ['strategic_implication_id'], unique=False)
    op.create_index(op.f('ix_requirements_sync_policy'), 'requirements', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_requirements_visibility_scope'), 'requirements', ['visibility_scope'], unique=False)
    op.create_table('generated_news',
    sa.Column('recommendation_item_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=False),
    sa.Column('content_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('generation_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_news_category'), 'generated_news', ['category'], unique=False)
    op.create_index(op.f('ix_generated_news_domain_code'), 'generated_news', ['domain_code'], unique=False)
    op.create_index(op.f('ix_generated_news_generation_status'), 'generated_news', ['generation_status'], unique=False)
    op.create_index(op.f('ix_generated_news_global_id'), 'generated_news', ['global_id'], unique=True)
    op.create_index(op.f('ix_generated_news_news_item_id'), 'generated_news', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_generated_news_recommendation_item_id'), 'generated_news', ['recommendation_item_id'], unique=False)
    op.create_index(op.f('ix_generated_news_sync_policy'), 'generated_news', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_generated_news_visibility_scope'), 'generated_news', ['visibility_scope'], unique=False)
    op.create_table('requirement_source_links',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('insight_id', sa.String(length=36), nullable=True),
    sa.Column('news_item_id', sa.String(length=36), nullable=True),
    sa.Column('raw_item_id', sa.String(length=36), nullable=True),
    sa.Column('link_type', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_source_links_insight_id'), 'requirement_source_links', ['insight_id'], unique=False)
    op.create_index(op.f('ix_requirement_source_links_link_type'), 'requirement_source_links', ['link_type'], unique=False)
    op.create_index(op.f('ix_requirement_source_links_news_item_id'), 'requirement_source_links', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_requirement_source_links_raw_item_id'), 'requirement_source_links', ['raw_item_id'], unique=False)
    op.create_index(op.f('ix_requirement_source_links_requirement_id'), 'requirement_source_links', ['requirement_id'], unique=False)
    op.create_table('topic_tasks',
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_tasks_assignee_user_id'), 'topic_tasks', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_topic_tasks_domain_code'), 'topic_tasks', ['domain_code'], unique=False)
    op.create_index(op.f('ix_topic_tasks_global_id'), 'topic_tasks', ['global_id'], unique=True)
    op.create_index(op.f('ix_topic_tasks_requirement_id'), 'topic_tasks', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_topic_tasks_status'), 'topic_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_topic_tasks_sync_policy'), 'topic_tasks', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_topic_tasks_visibility_scope'), 'topic_tasks', ['visibility_scope'], unique=False)
    op.create_table('daily_report_items',
    sa.Column('daily_report_id', sa.String(length=36), nullable=False),
    sa.Column('generated_news_id', sa.String(length=36), nullable=False),
    sa.Column('adoption_status', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('editor_title', sa.Text(), nullable=True),
    sa.Column('editor_summary', sa.Text(), nullable=True),
    sa.Column('editor_key_points', sa.Text(), nullable=True),
    sa.Column('editor_content_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('editor_notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['generated_news_id'], ['generated_news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_report_items_adoption_status'), 'daily_report_items', ['adoption_status'], unique=False)
    op.create_index(op.f('ix_daily_report_items_daily_report_id'), 'daily_report_items', ['daily_report_id'], unique=False)
    op.create_index(op.f('ix_daily_report_items_domain_code'), 'daily_report_items', ['domain_code'], unique=False)
    op.create_index(op.f('ix_daily_report_items_generated_news_id'), 'daily_report_items', ['generated_news_id'], unique=False)
    op.create_index(op.f('ix_daily_report_items_global_id'), 'daily_report_items', ['global_id'], unique=True)
    op.create_index(op.f('ix_daily_report_items_sync_policy'), 'daily_report_items', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_daily_report_items_visibility_scope'), 'daily_report_items', ['visibility_scope'], unique=False)
    op.create_table('comments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=True),
    sa.Column('daily_report_item_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('root_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_item_id'], ['daily_report_items.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_daily_report_item_id'), 'comments', ['daily_report_item_id'], unique=False)
    op.create_index(op.f('ix_comments_news_item_id'), 'comments', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_root_id'), 'comments', ['root_id'], unique=False)
    op.create_index(op.f('ix_comments_status'), 'comments', ['status'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('export_job_items',
    sa.Column('export_job_id', sa.String(length=36), nullable=False),
    sa.Column('daily_report_item_id', sa.String(length=36), nullable=False),
    sa.Column('generated_news_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=False),
    sa.Column('sql_sequence', sa.Integer(), nullable=False),
    sa.Column('sql_table', sa.String(length=128), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_item_id'], ['daily_report_items.id'], ),
    sa.ForeignKeyConstraint(['export_job_id'], ['export_jobs.id'], ),
    sa.ForeignKeyConstraint(['generated_news_id'], ['generated_news.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_job_items_daily_report_item_id'), 'export_job_items', ['daily_report_item_id'], unique=False)
    op.create_index(op.f('ix_export_job_items_export_job_id'), 'export_job_items', ['export_job_id'], unique=False)
    op.create_index(op.f('ix_export_job_items_generated_news_id'), 'export_job_items', ['generated_news_id'], unique=False)
    op.create_index(op.f('ix_export_job_items_news_item_id'), 'export_job_items', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_export_job_items_status'), 'export_job_items', ['status'], unique=False)
    op.create_table('ratings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=True),
    sa.Column('daily_report_item_id', sa.String(length=36), nullable=True),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_item_id'], ['daily_report_items.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_daily_report_item_id'), 'ratings', ['daily_report_item_id'], unique=False)
    op.create_index(op.f('ix_ratings_dimension'), 'ratings', ['dimension'], unique=False)
    op.create_index(op.f('ix_ratings_news_item_id'), 'ratings', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=True),
    sa.Column('daily_report_item_id', sa.String(length=36), nullable=True),
    sa.Column('reaction_type', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_item_id'], ['daily_report_items.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactions_daily_report_item_id'), 'reactions', ['daily_report_item_id'], unique=False)
    op.create_index(op.f('ix_reactions_news_item_id'), 'reactions', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_reactions_reaction_type'), 'reactions', ['reaction_type'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    op.create_table('weekly_report_items',
    sa.Column('weekly_report_id', sa.String(length=36), nullable=False),
    sa.Column('daily_report_item_id', sa.String(length=36), nullable=True),
    sa.Column('generated_news_id', sa.String(length=36), nullable=True),
    sa.Column('adoption_status', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('editor_title', sa.Text(), nullable=True),
    sa.Column('editor_summary', sa.Text(), nullable=True),
    sa.Column('editor_content_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_code', sa.String(length=64), nullable=False),
    sa.Column('visibility_scope', sa.String(length=32), nullable=False),
    sa.Column('sync_policy', sa.String(length=32), nullable=False),
    sa.Column('global_id', sa.String(length=64), nullable=False),
    sa.Column('origin_instance_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_item_id'], ['daily_report_items.id'], ),
    sa.ForeignKeyConstraint(['generated_news_id'], ['generated_news.id'], ),
    sa.ForeignKeyConstraint(['weekly_report_id'], ['weekly_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_report_items_adoption_status'), 'weekly_report_items', ['adoption_status'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_daily_report_item_id'), 'weekly_report_items', ['daily_report_item_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_domain_code'), 'weekly_report_items', ['domain_code'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_generated_news_id'), 'weekly_report_items', ['generated_news_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_global_id'), 'weekly_report_items', ['global_id'], unique=True)
    op.create_index(op.f('ix_weekly_report_items_sync_policy'), 'weekly_report_items', ['sync_policy'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_visibility_scope'), 'weekly_report_items', ['visibility_scope'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_weekly_report_id'), 'weekly_report_items', ['weekly_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_report_items_weekly_report_id'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_visibility_scope'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_sync_policy'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_global_id'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_generated_news_id'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_domain_code'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_daily_report_item_id'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_adoption_status'), table_name='weekly_report_items')
    op.drop_table('weekly_report_items')
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_reaction_type'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_news_item_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_daily_report_item_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_news_item_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_dimension'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_daily_report_item_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_export_job_items_status'), table_name='export_job_items')
    op.drop_index(op.f('ix_export_job_items_news_item_id'), table_name='export_job_items')
    op.drop_index(op.f('ix_export_job_items_generated_news_id'), table_name='export_job_items')
    op.drop_index(op.f('ix_export_job_items_export_job_id'), table_name='export_job_items')
    op.drop_index(op.f('ix_export_job_items_daily_report_item_id'), table_name='export_job_items')
    op.drop_table('export_job_items')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_status'), table_name='comments')
    op.drop_index(op.f('ix_comments_root_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_news_item_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_daily_report_item_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_daily_report_items_visibility_scope'), table_name='daily_report_items')
    op.drop_index(op.f('ix_daily_report_items_sync_policy'), table_name='daily_report_items')
    op.drop_index(op.f('ix_daily_report_items_global_id'), table_name='daily_report_items')
    op.drop_index(op.f('ix_daily_report_items_generated_news_id'), table_name='daily_report_items')
    op.drop_index(op.f('ix_daily_report_items_domain_code'), table_name='daily_report_items')
    op.drop_index(op.f('ix_daily_report_items_daily_report_id'), table_name='daily_report_items')
    op.drop_index(op.f('ix_daily_report_items_adoption_status'), table_name='daily_report_items')
    op.drop_table('daily_report_items')
    op.drop_index(op.f('ix_topic_tasks_visibility_scope'), table_name='topic_tasks')
    op.drop_index(op.f('ix_topic_tasks_sync_policy'), table_name='topic_tasks')
    op.drop_index(op.f('ix_topic_tasks_status'), table_name='topic_tasks')
    op.drop_index(op.f('ix_topic_tasks_requirement_id'), table_name='topic_tasks')
    op.drop_index(op.f('ix_topic_tasks_global_id'), table_name='topic_tasks')
    op.drop_index(op.f('ix_topic_tasks_domain_code'), table_name='topic_tasks')
    op.drop_index(op.f('ix_topic_tasks_assignee_user_id'), table_name='topic_tasks')
    op.drop_table('topic_tasks')
    op.drop_index(op.f('ix_requirement_source_links_requirement_id'), table_name='requirement_source_links')
    op.drop_index(op.f('ix_requirement_source_links_raw_item_id'), table_name='requirement_source_links')
    op.drop_index(op.f('ix_requirement_source_links_news_item_id'), table_name='requirement_source_links')
    op.drop_index(op.f('ix_requirement_source_links_link_type'), table_name='requirement_source_links')
    op.drop_index(op.f('ix_requirement_source_links_insight_id'), table_name='requirement_source_links')
    op.drop_table('requirement_source_links')
    op.drop_index(op.f('ix_generated_news_visibility_scope'), table_name='generated_news')
    op.drop_index(op.f('ix_generated_news_sync_policy'), table_name='generated_news')
    op.drop_index(op.f('ix_generated_news_recommendation_item_id'), table_name='generated_news')
    op.drop_index(op.f('ix_generated_news_news_item_id'), table_name='generated_news')
    op.drop_index(op.f('ix_generated_news_global_id'), table_name='generated_news')
    op.drop_index(op.f('ix_generated_news_generation_status'), table_name='generated_news')
    op.drop_index(op.f('ix_generated_news_domain_code'), table_name='generated_news')
    op.drop_index(op.f('ix_generated_news_category'), table_name='generated_news')
    op.drop_table('generated_news')
    op.drop_index(op.f('ix_requirements_visibility_scope'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_sync_policy'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_strategic_implication_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_status'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_priority'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_owner_user_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_global_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_domain_code'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_recommendation_items_visibility_scope'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_sync_policy'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_selected'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_run_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_news_item_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_global_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_domain_code'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_dedupe_group_item_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_dedupe_group_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_strategic_implications_visibility_scope'), table_name='strategic_implications')
    op.drop_index(op.f('ix_strategic_implications_sync_policy'), table_name='strategic_implications')
    op.drop_index(op.f('ix_strategic_implications_insight_id'), table_name='strategic_implications')
    op.drop_index(op.f('ix_strategic_implications_implication_type'), table_name='strategic_implications')
    op.drop_index(op.f('ix_strategic_implications_global_id'), table_name='strategic_implications')
    op.drop_index(op.f('ix_strategic_implications_domain_code'), table_name='strategic_implications')
    op.drop_table('strategic_implications')
    op.drop_index(op.f('ix_dedupe_group_items_news_item_id'), table_name='dedupe_group_items')
    op.drop_index(op.f('ix_dedupe_group_items_dedupe_group_id'), table_name='dedupe_group_items')
    op.drop_table('dedupe_group_items')
    op.drop_index(op.f('ix_insights_visibility_scope'), table_name='insights')
    op.drop_index(op.f('ix_insights_sync_policy'), table_name='insights')
    op.drop_index(op.f('ix_insights_news_item_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_insight_type'), table_name='insights')
    op.drop_index(op.f('ix_insights_global_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_domain_code'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_dedupe_groups_visibility_scope'), table_name='dedupe_groups')
    op.drop_index(op.f('ix_dedupe_groups_sync_policy'), table_name='dedupe_groups')
    op.drop_index(op.f('ix_dedupe_groups_global_id'), table_name='dedupe_groups')
    op.drop_index(op.f('ix_dedupe_groups_domain_code'), table_name='dedupe_groups')
    op.drop_index(op.f('ix_dedupe_groups_dedupe_key'), table_name='dedupe_groups')
    op.drop_table('dedupe_groups')
    op.drop_index(op.f('ix_news_items_visibility_scope'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_sync_policy'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_source_type'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_raw_item_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_normalization_status'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_global_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_domain_code'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_dedupe_key'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_data_source_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_active'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sync_conflicts_sync_run_id'), table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_status'), table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_object_type'), table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_object_id'), table_name='sync_conflicts')
    op.drop_table('sync_conflicts')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_raw_items_visibility_scope'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_sync_policy'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_source_type'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_global_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_fetched_at'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_entry_key'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_domain_code'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_data_source_id'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_index(op.f('ix_export_jobs_visibility_scope'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_sync_policy'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_requested_by_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_global_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_export_type'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_domain_code'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_editorial_actions_user_id'), table_name='editorial_actions')
    op.drop_index(op.f('ix_editorial_actions_object_type'), table_name='editorial_actions')
    op.drop_index(op.f('ix_editorial_actions_object_id'), table_name='editorial_actions')
    op.drop_index(op.f('ix_editorial_actions_action_type'), table_name='editorial_actions')
    op.drop_table('editorial_actions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_weekly_reports_week_key'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_visibility_scope'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_sync_policy'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_status'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_global_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_domain_code'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_global_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_provider'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_no'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_runs_target_instance_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_source_instance_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_package_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_direction'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_sync_outbox_visibility_scope'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_sync_policy'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_status'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_operation'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_object_type'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_object_id'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_event_id'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_domain_code'), table_name='sync_outbox')
    op.drop_table('sync_outbox')
    op.drop_index(op.f('ix_sync_inbox_status'), table_name='sync_inbox')
    op.drop_index(op.f('ix_sync_inbox_source_instance_id'), table_name='sync_inbox')
    op.drop_index(op.f('ix_sync_inbox_object_type'), table_name='sync_inbox')
    op.drop_index(op.f('ix_sync_inbox_object_id'), table_name='sync_inbox')
    op.drop_index(op.f('ix_sync_inbox_event_id'), table_name='sync_inbox')
    op.drop_table('sync_inbox')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_recommendation_runs_visibility_scope'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_sync_policy'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_status'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_run_key'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_global_id'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_domain_code'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_data_sources_visibility_scope'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_sync_policy'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_global_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_domain_code'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_daily_reports_visibility_scope'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_sync_policy'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_status'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_global_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_domain_code'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_day_key'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
