from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime, time
from html import unescape
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.models.common import utc_now
from app.models.content import GeneratedNews, NewsItem
from app.models.export import ExportJob, ExportJobItem
from app.models.reports import DailyReport, DailyReportItem

COMPANY_SQL_CONTENT_FIELDS = (
    "background",
    "effects",
    "eventSummary",
    "technologyAndInnovation",
    "valueAndImpact",
)


class DailyReportNotFoundError(ValueError):
    pass


class DailyReportNotPublishedError(ValueError):
    pass


class DailyReportGenerationNotReadyError(ValueError):
    pass


@dataclass(frozen=True)
class CompanySqlExportResult:
    export_job: ExportJob
    sql_text: str
    item_count: int
    statement_count: int


@dataclass(frozen=True)
class CompanySqlStatement:
    table: str
    sql: str


def generate_company_sql_for_daily_report(
    session: Session,
    daily_report_id: str,
    requested_by_id: str | None = None,
) -> CompanySqlExportResult:
    report = _load_daily_report(session, daily_report_id)
    if report is None:
        raise DailyReportNotFoundError(f"Daily report not found: {daily_report_id}")
    if report.status != "published":
        raise DailyReportNotPublishedError(
            "Company SQL export only supports published daily reports.",
        )

    adopted_items = sorted(
        (item for item in report.items if item.adoption_status == 2),
        key=lambda item: (item.sort_order, item.created_at, item.id),
    )
    not_ready = [
        item
        for item in adopted_items
        if item.generated_news.generation_status != "ready"
        or item.generated_news.generated_by.startswith("rule_v1")
    ]
    if not_ready:
        raise DailyReportGenerationNotReadyError(
            "Company SQL export requires adopted items to be generated by the LLM and marked ready.",
        )

    started_at = utc_now()
    export_category_mode = _export_category_mode(session, report)
    export_job = ExportJob(
        workspace_code=report.workspace_code,
        domain_code=report.domain_code,
        visibility_scope=report.visibility_scope,
        sync_policy=report.sync_policy,
        export_type="company_sql",
        status="running",
        requested_by_id=requested_by_id,
        params_json={
            "daily_report_id": report.id,
            "day_key": report.day_key,
            "workspace_code": report.workspace_code,
            "adoption_status": 2,
            "content_fields": list(COMPANY_SQL_CONTENT_FIELDS),
            "export_category_mode": export_category_mode,
        },
        started_at=started_at,
    )
    session.add(export_job)
    session.flush()

    item_blocks: list[str] = []
    statement_count = 0
    for item in adopted_items:
        block, statements = _sql_block_for_item(item, export_category_mode, report.day_key)
        item_blocks.append(block)
        for statement in statements:
            statement_count += 1
            session.add(
                ExportJobItem(
                    export_job=export_job,
                    daily_report_item=item,
                    generated_news=item.generated_news,
                    news_item=item.generated_news.news_item,
                    sql_sequence=statement_count,
                    sql_table=statement.table,
                    sql_text=statement.sql,
                    status="completed",
                ),
            )

    sql_text = _sql_header(started_at, report, len(adopted_items), statement_count) + "".join(
        item_blocks,
    )
    export_job.status = "completed"
    export_job.completed_at = utc_now()
    export_job.result_json = {
        "daily_report_id": report.id,
        "day_key": report.day_key,
        "item_count": len(adopted_items),
        "statement_count": statement_count,
        "sql_text": sql_text,
        "sql_tables": [
            "ai_journal",
            "ai_journal_focus",
            "ai_journal_analysis",
            "t_news_data_info",
        ],
    }
    session.flush()
    return CompanySqlExportResult(
        export_job=export_job,
        sql_text=sql_text,
        item_count=len(adopted_items),
        statement_count=statement_count,
    )


def _load_daily_report(session: Session, daily_report_id: str) -> DailyReport | None:
    return session.scalar(
        select(DailyReport)
        .options(
            selectinload(DailyReport.items)
            .selectinload(DailyReportItem.generated_news)
            .selectinload(GeneratedNews.news_item)
            .selectinload(NewsItem.raw_item),
        )
        .where(DailyReport.id == daily_report_id),
    )


def _sql_header(
    generated_at: datetime,
    report: DailyReport,
    item_count: int,
    statement_count: int,
) -> str:
    return (
        "-- InfoWatchtower Company SQL Preview\n"
        f"-- 工作台: {report.workspace_code}\n"
        f"-- 日期范围: {report.day_key}\n"
        f"-- 生成时间: {generated_at.astimezone(UTC).strftime('%Y-%m-%d %H:%M:%S')}\n"
        "-- 导出规则: 已发布日报；仅 adoption_status = 2；generated_news.generation_status = ready；非 rule_v1 fallback。\n"
        "-- 表顺序: ai_journal -> ai_journal_focus -> ai_journal_analysis -> t_news_data_info\n"
        "-- 日期规则: created_at 使用 'YYYY-MM-DD HH:MM:SS'；缺失发布时间兜底为日报 day_key 09:00:00；禁止 NULL/STR_TO_DATE。\n"
        "-- 校验基准: outputs/sql/previews/planning_intel_2026-05-05_company_sql_preview.sql\n"
        f"-- 汇总: {item_count} 条新闻，{statement_count} 条 SQL 语句。\n\n"
    )


def _sql_block_for_item(
    item: DailyReportItem,
    export_category_mode: str,
    report_day_key: str,
) -> tuple[str, list[CompanySqlStatement]]:
    generated = item.generated_news
    news_item = generated.news_item
    raw_item = news_item.raw_item
    source_url = _first_text(raw_item.source_url, news_item.source_url, generated.source_url)
    source_title = _clean_export_text(
        _first_text(raw_item.source_title, news_item.source_title, "自动同步抓取"),
    )
    raw_content = _clean_export_text(_first_text(raw_item.raw_content, news_item.content))
    focus_id = _safe_int(news_item.focus_id)
    created_at = _mysql_datetime(
        raw_item.published_at
        or news_item.published_at
        or _report_day_fallback_datetime(report_day_key),
    )

    raw_url_val = escape_sql_string(source_url)
    raw_title_val = escape_sql_string(source_title)
    raw_content_val = escape_sql_string(raw_content)

    title_val = escape_sql_string(item.editor_title or generated.title or "无标题")
    summary_val = escape_sql_string(item.editor_summary or generated.summary or "")
    key_points_val = escape_sql_string(item.editor_key_points or generated.key_points or "")
    category_val = escape_sql_string(_export_category(item, export_category_mode))
    content_json_val = escape_sql_string(
        json.dumps(_company_content_json(item), ensure_ascii=False),
    )

    sql_journal = (
        "INSERT IGNORE INTO ai_journal (source_url, source_title, content, created_at) "
        f"VALUES ({raw_url_val}, {raw_title_val}, {raw_content_val}, {created_at});\n"
    )
    sql_focus = (
        "INSERT IGNORE INTO ai_journal_focus (journal_id, focus_id) "
        f"SELECT id, {focus_id} FROM ai_journal WHERE source_url = {raw_url_val} LIMIT 1;\n"
    )
    sql_analysis = (
        "INSERT INTO ai_journal_analysis "
        "(journal_id, category, title, summary, key_points, content_json, source_url, created_at) "
        f"SELECT id, {category_val}, {title_val}, {summary_val}, "
        f"{key_points_val}, {content_json_val}, {raw_url_val}, {created_at} "
        f"FROM ai_journal WHERE source_url = {raw_url_val} LIMIT 1;\n"
    )
    sql_data_info = (
        "INSERT INTO t_news_data_info "
        "(catalog_id, journal_id, data, adoption_status, category, title, summary, "
        "key_points, content_json, source_url) "
        f"SELECT NULL, id, NULL, {int(item.adoption_status)}, {category_val}, {title_val}, "
        f"{summary_val}, {key_points_val}, {content_json_val}, {raw_url_val} "
        f"FROM ai_journal WHERE source_url = {raw_url_val} LIMIT 1;\n"
    )
    statements = [
        CompanySqlStatement("ai_journal", sql_journal),
        CompanySqlStatement("ai_journal_focus", sql_focus),
        CompanySqlStatement("ai_journal_analysis", sql_analysis),
        CompanySqlStatement("t_news_data_info", sql_data_info),
    ]
    block = (
        f"-- [写入数据 Focus_ID: {focus_id}]\n"
        + "".join(statement.sql for statement in statements)
        + "\n"
    )
    return block, statements


def _export_category_mode(session: Session, report: DailyReport) -> str:
    return "news_primary"


def _export_category(item: DailyReportItem, export_category_mode: str) -> str:
    generated = item.generated_news
    category = generated.category or ""
    if category in AI_SQL_CATEGORIES:
        return category
    content_json = generated.content_json or {}
    legacy_category = _first_text(
        content_json.get("legacy_ai_category"),
        content_json.get("sql_category"),
    )
    if legacy_category in AI_SQL_CATEGORIES:
        return legacy_category
    return _legacy_ai_category_for_item(item)


AI_SQL_CATEGORIES = {
    "AI Infra",
    "AI 应用",
    "测评技术",
    "大厂动态",
    "模型",
    "算法",
    "推理加速",
    "训练技术",
    "智能体",
    "基础竞争力",
}


def _legacy_ai_category_for_item(item: DailyReportItem) -> str:
    generated = item.generated_news
    text = " ".join(
        [
            generated.category or "",
            item.editor_title or generated.title or "",
            item.editor_summary or generated.summary or "",
            item.editor_key_points or generated.key_points or "",
            json.dumps(_company_content_json(item), ensure_ascii=False),
        ],
    ).lower()
    rules = [
        ("智能体", ("agent", "智能体", "mcp", "a2a", "rag")),
        ("推理加速", ("inference", "推理", "kv cache", "serving", "吞吐", "延迟")),
        ("训练技术", ("training", "训练", "fine-tuning", "finetune", "后训练")),
        ("测评技术", ("benchmark", "评测", "evaluation", "eval", "数据集")),
        ("AI Infra", ("infra", "infrastructure", "gpu", "hbm", "cxl", "集群", "数据中心")),
        ("模型", ("model", "模型", "llm", "多模态", "vlm", "vla")),
        ("算法", ("algorithm", "算法", "优化", "architecture", "架构")),
        ("大厂动态", ("openai", "google", "deepmind", "meta", "microsoft", "anthropic", "amazon")),
        ("AI 应用", ("应用", "assistant", "copilot", "workflow", "case")),
    ]
    for category, keywords in rules:
        if any(keyword in text for keyword in keywords):
            return category
    return "基础竞争力"


def _company_content_json(item: DailyReportItem) -> dict[str, str]:
    generated_content = item.generated_news.content_json or {}
    editor_content = item.editor_content_json or {}
    merged = {**generated_content, **editor_content}
    return {
        field: _stringify_content_value(merged.get(field, ""))
        for field in COMPANY_SQL_CONTENT_FIELDS
    }


def _stringify_content_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False)


def _first_text(*values: Any) -> str:
    for value in values:
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return ""


def _clean_export_text(value: Any) -> str:
    text = unescape(str(value or ""))
    text = re.sub(r"<script\b[^>]*>.*?</script>", " ", text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"<style\b[^>]*>.*?</style>", " ", text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"<br\s*/?>", "\n", text, flags=re.IGNORECASE)
    text = re.sub(r"</p\s*>", "\n", text, flags=re.IGNORECASE)
    text = re.sub(r"<[^>]+>", " ", text)
    return " ".join(text.split())


def _safe_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _mysql_datetime(value: datetime | None) -> str:
    if value is None:
        return "NULL"
    if value.tzinfo is None:
        value = value.replace(tzinfo=UTC)
    return f"'{value.astimezone(UTC).strftime('%Y-%m-%d %H:%M:%S')}'"


def _report_day_fallback_datetime(day_key: str) -> datetime | None:
    try:
        report_day = datetime.strptime(day_key, "%Y-%m-%d").date()
    except ValueError:
        return None
    return datetime.combine(report_day, time(hour=9), tzinfo=UTC)


def escape_sql_string(text: Any) -> str:
    if text is None:
        return "NULL"
    escaped_text = str(text).replace("\\", "\\\\").replace("'", "''")
    return f"'{escaped_text}'"
